module.exports = {
  ALL_BRANDS_RECEIVED: "ALL_BRANDS_RECEIVED",
  ALL_CATEGORIES_RECEIVED: "ALL_CATEGORIES_RECEIVED",
  BRANDS_FILTER_RECEIVED: "BRANDS_FILTER_RECEIVED",
  CATEGORIES_FILTER_RECEIVED: "CATEGORIES_FILTER_RECEIVED"
};
